'use client'

import useSWR from 'swr'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Brain, BookOpen, Target, BarChart3, Loader2 } from 'lucide-react'

const fetcher = (url: string) => fetch(url).then(r => r.json())

const categoryIcons: Record<string, React.ReactNode> = {
  study: <BookOpen className="h-5 w-5 text-primary" />,
  practice: <Target className="h-5 w-5 text-accent" />,
  strategy: <Brain className="h-5 w-5 text-chart-3" />,
  revision: <BarChart3 className="h-5 w-5 text-chart-5" />,
}

const priorityColors: Record<string, string> = {
  high: 'bg-destructive/10 text-destructive border-destructive/20',
  medium: 'bg-chart-3/10 text-chart-3 border-chart-3/20',
  low: 'bg-accent/10 text-accent border-accent/20',
}

export default function RecommendationsPage() {
  const { data, isLoading } = useSWR('/api/recommendations', fetcher)

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground flex items-center gap-2">
          <Brain className="h-6 w-6 text-primary" />
          AI Study Recommendations
        </h1>
        <p className="text-muted-foreground mt-1">
          Personalized recommendations generated by AI based on your performance data.
        </p>
      </div>

      {isLoading ? (
        <div className="flex items-center justify-center py-20">
          <Loader2 className="h-6 w-6 animate-spin text-primary" />
          <span className="ml-2 text-muted-foreground">Generating AI recommendations...</span>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {(data?.recommendations || []).map((rec: { title: string; description: string; priority: string; category: string }, i: number) => (
            <Card key={i} className="transition-all hover:shadow-md">
              <CardHeader className="flex flex-row items-start gap-4 pb-2">
                <div className="flex items-center justify-center w-10 h-10 rounded-lg bg-secondary">
                  {categoryIcons[rec.category] || <Brain className="h-5 w-5 text-primary" />}
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <CardTitle className="text-base font-semibold text-foreground">{rec.title}</CardTitle>
                    <Badge variant="outline" className={priorityColors[rec.priority] || ''}>
                      {rec.priority}
                    </Badge>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="pl-20">
                <p className="text-sm text-muted-foreground leading-relaxed">{rec.description}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <p className="text-xs text-muted-foreground italic">
        AI-assisted guidance based on available performance data. Recommendations are suggestions and should be adapted to your study style.
      </p>
    </div>
  )
}
